### ISSUE TITLE
NVRAM file causes the core to start with black screen

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/Arcade-BurgerTime_MiSTer#20]
I've encountered a weird issue with Burger Time. The core works perfectly fine when you launch it the first time. Saving core settings creates an .nvm file used for score saving. Exiting the core and starting it again then results in a black screen. You can hear the loud beep, indicating that the core is running and it's just the video which is missing. Pressing Reset in OSD fixes the issue and everything appars normally.
Going to config/nvram and deleting the .nvm file for Burger Time fixes the issue with black screen, but it reappears once a new file is generated.
Furthermore, there seems to be some side effect caused by Pause when OSD is open option. Having it set to Off somehow disables the fix with resetting the game, as the game just resets with black screen still present. Returning its value to On makes removes such issue.

**Comment by siffland** [comment]
I can confirm this, it happens in my installation as well.

**Comment by sorgelig** [comment]
@JimmyStones

**Comment by JimmyStones** [comment]
@Thelypody / @siffland I can't replicate this on the latest version of the core :(  Could you confirm that you are running the latest version of the core (20230310) and the MiSTer framework etc?  If you can generate and send me a copy of the .nvm that causes the black screen I'll see if there are any clues there.

**Comment by Thelypody** [comment]
MiSTer 20230223, BurgerTime 20230310, completely fresh setup (had a nasty SD card crash recently which wiped all my data).
Entered the core for the first time: core boots properly. Did not touch any settings, saved settings to create a config file (btime.CFG is just zeroes). Rebooted to the main menu and launched Burger Time again: black screen with a beep.

.nvm file: [Burger Time (Set 1).zip](https://github.com/MiSTer-devel/Arcade-BurgerTime_MiSTer/files/11008434/Burger.Time.Set.1.zip)

**Comment by JimmyStones** [comment]
Ehh.. I don't have a fresh install to test on but I'm on the same versions, and performing that process doesn't cause the issue for me!   Additionally if I put your .nvm on my MiSTer the game loads fine (and the content of the file is correct, same as it generates from scratch on mine).  

Can you try using this file just to rule out a file issue please?

[Burger Time (Set 1).zip](https://github.com/MiSTer-devel/Arcade-BurgerTime_MiSTer/files/11008532/Burger.Time.Set.1.zip)

**Comment by Thelypody** [comment]
Your .nvm file results in the same issue for me.

**Comment by JimmyStones** [comment]
Ok we have at least ruled out a problem with the highscore **save** then, problem is with loading it in...  I have to assume it has been working fine for many other people as well as me or we would have had more issues reported since 2021 when I implemented it!

Can you try this .mra?
[Burger Time (Set 1).zip](https://github.com/MiSTer-devel/Arcade-BurgerTime_MiSTer/files/11008569/Burger.Time.Set.1.zip)

(I've added a bit of extra delay around the read process so the game pauses the CPU for a few more cycles, as I managed to replicate the behaviour if I lowered the number on mine... so maybe the opposite will help for you!)

**Comment by Thelypody** [comment]
No luck, still the black screen after saving settings and restarting.

**Comment by JimmyStones** [comment]
Ok, one last try with numbers dialled up to 11?

[Burger Time (Set 1).zip](https://github.com/MiSTer-devel/Arcade-BurgerTime_MiSTer/files/11008608/Burger.Time.Set.1.zip)

**Comment by Thelypody** [comment]
Same thing, no difference to me.

**Comment by JimmyStones** [comment]
Oof, ok, slightly difference approach - this one delays the hiscore load. Try it with my .nvm - for me it shows up with the default high scores at first but then it should should show my test scores after the screen changes.

[Burger Time (Set 1).zip](https://github.com/MiSTer-devel/Arcade-BurgerTime_MiSTer/files/11008671/Burger.Time.Set.1.zip)

**Comment by Thelypody** [comment]
Okay, this one is finally working. Restarting the core displays default high score table at last. I set up all settings to my liking and played until I got a score high enough to display it. Saving and restarting now produces a default high score table at first but it updates to my high scores when I insert a coin.

**Comment by JimmyStones** [comment]
Progress!

Would you be ok to test a bit further, as it's not ideal having the delay that long?

In the MRA there is this section:
```
<rom index="3" md5="none">
	<part>
	00 20 00 00 00 FF 00 02 00 02 00 01 00 FF 02 00
	00 00 00 33 00 27 00 FF
	</part>
</rom>
```

The first 4 bytes of data are the delay - could you try progressively lowering the second value from 20 (it's hex so 1F, 1E, 1D, 1C, 1B, 1A, 19 etc..) and seeing when the black screen starts triggering?

**Comment by Thelypody** [comment]
Black screen happens at 0F. Interestingly, up until 10 it was displaying default high score names (but proper high score values). At 10 it launches with my names already in the table. Going just one value lower triggers the black screen, so I assume that 10 is the sweet spot.

**Comment by JimmyStones** [comment]
So weird, the only thing I can assume is my MiSTer is running a bit slower than yours somehow!  I'll push an update with that new value, cheers for testing.

**Comment by Thelypody** [comment]
Just played around with published .mra, everything seems to work properly. Thanks a lot for the fix!

**Comment by JimmyStones** [comment]
> 

Nice, no problem at all 👍
