### ISSUE TITLE
Directional inputs are not mapped correctly when you put game in vertical positioning.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Arcade-BurgerTime_MiSTer#8]
All the other Arcade cores that let you position vertically for tate mode correct their directional inputs on the fly when you map initially for horizontal mode.  This core does not do that and so the directions get all wonky in this mode.

**Comment by alanswx** [comment]
This should be fixed. Please close the issue if it is fixed.

**Comment by SegaSnatcher** [comment]
Latest release fixed this issue, thank you.
